### PR TITLE
Fix embeds in Chrome

### LINKED ISSUE #383: Add MutationObserver to nested iframe previews
Also need to add the [`credentialless`](https://developer.mozilla.org/en-US/docs/Web/Security/IFrame_credentialless) attribute to make YouTube embeds working.

### PR DESCRIPTION
**Pull request by swissspidy**
See #383 — this only fixes YouTube embeds but not Twitter embeds for example

Props @adamziel for the hint

Updates the `MutationObserver` instance to work inside the `editor-canvas__iframe` iframe and apply attributes to the `.components-sandbox` iframe as well.

Attributes do **not** need to be added to the YouTube iframe itself apparently.

All I had to do was ensure the `.components-sandbox` iframe has a `src` attribute set, even if it's empty.

To-do:

- [ ] Add tests

Demo:

Screenshot 2024-03-17 at 19 53 50

### CODE REVIEW

**Comment by swissspidy** [comment]
https://github.com/WICG/anonymous-iframe/issues/14 gave me the right idea:

The sandbox iframe should be credentialless, but the tweet script itself should not be modified.

Tweet embeds are working now!

**Comment by swissspidy** [comment]
Just to clarify: this is only for Chrome and browsers that support `credentialless`, so the twitter embed is still broken in Safari and Firefox.

See https://developer.chrome.com/blog/iframe-credentialless

**Comment by adamziel** [comment]
Good explorations here @swissspidy! TIL about `Cross-Origin-Embedder-Policy: credentialless`. It seems like the cross origin separation is still settling down – I wonder how these platforms will adjust their embeds over time.

**Comment by muslehsalah11** [comment]
https://www.asyallakora.com

**Pull request merged**
